SolVueWeb/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SolVueWeb.Models
{
    public class Usuario
    {
        [Key]
        public int UsuarioId { get; set; }

        [Required(ErrorMessage ="El campo {0} es requerido")]
        [StringLength(50, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 2)]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(50, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 2)]
        [Display(Name ="Apellido Paterno")]
        public string ApellidoPat { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(50, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 2)]
        [Display(Name = "Apellido Materno")]
        public string ApellidoMat { get; set; }

        [Index("NombreUsuarioIndex", IsUnique=true)]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name ="E-Mail")]
        [StringLength(100, ErrorMessage ="El campo {0} debe contener maximo {1} y minimo {2} caracteres",MinimumLength =7)]
        [DataType(DataType.EmailAddress)]
        public string NombreUsuario { get; set; }

        //public int Ficha { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(20, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 7)]
        public string Telefono { get; set; }

        //[StringLength(20, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 7)]
        //public string Extension { get; set; }

        //[StringLength(20, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 7)]
        //public string Celular { get; set; }

        ////public int DependenciaId { get; set; }

        //[StringLength(50, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 10)]
        //public string Cargo { get; set; }

        [DataType(DataType.ImageUrl)]
        [StringLength(200, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 5)]
        public string Foto { get; set; }

        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}

SolVueWeb/Models/UsuarioView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SolVueWeb.Models
{
    public class UsuarioView
    {
        public int UsuarioId { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(50, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 2)]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(50, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 2)]
        [Display(Name = "Apellido Paterno")]
        public string ApellidoPat { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(50, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 2)]
        [Display(Name = "Apellido Materno")]
        public string ApellidoMat { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "E-Mail")]
        [StringLength(100, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 7)]
        [DataType(DataType.EmailAddress)]
        public string NombreUsuario { get; set; }

        public int Ficha { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(20, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 7)]
        public string Telefono { get; set; }

        [StringLength(20, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 7)]
        public string Extension { get; set; }

        [StringLength(20, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 7)]
        public string Celular { get; set; }

        public int DependenciaId { get; set; }

        [StringLength(50, ErrorMessage = "El campo {0} debe contener maximo {1} y minimo {2} caracteres", MinimumLength = 10)]
        public string Cargo { get; set; }

        public HttpPostedFileBase Foto { get; set; }

    }
}

SolVueWeb/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SolVueWeb.Models;
using System.IO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace SolVueWeb.Controllers
{

    public class UsuariosController : Controller
    {
        private SolVueContext db = new SolVueContext();

        [Authorize(Roles = "User")]
        [HttpGet]
        public ActionResult MiPerfil()
        {
            var usuario = db.Usuarios
                .Where(u => u.NombreUsuario == this.User.Identity.Name)
                .FirstOrDefault();
            var vista = new UsuarioPerfilView
            {
                Nombre=usuario.Nombre,
                ApellidoPat=usuario.ApellidoPat,
                ApellidoMat=usuario.ApellidoMat,
                NombreUsuario=usuario.NombreUsuario,
                //Ficha=usuario.Ficha,
                Telefono=usuario.Telefono,
                //Extension=usuario.Extension,
                //Celular=usuario.Celular,
                //DependenciaId=usuario.DependenciaId,
                //Cargo=usuario.Cargo,
                Foto=usuario.Foto,
                UsuarioId = usuario.UsuarioId,

            };
            return View(vista);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MiPerfil(UsuarioPerfilView vista )
        {
            if (ModelState.IsValid)
            {
                //Upload
                string path = string.Empty;
                string pic = string.Empty;

                if (vista.NuevaFoto != null)
                {
                    pic = Path.GetFileName(vista.NuevaFoto.FileName);
                    path = Path.Combine(Server.MapPath("~/Content/Fotos"), pic);

                    vista.NuevaFoto.SaveAs(path); //se guarda la foto local

                    using (MemoryStream ms = new MemoryStream()) //se guarda en el servidor la foto
                    {
                        vista.NuevaFoto.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }
                }
                var usuario = db.Usuarios.Find(vista.UsuarioId);

                usuario.Nombre = vista.Nombre;
                usuario.ApellidoPat = vista.ApellidoPat;
                usuario.ApellidoMat = vista.ApellidoMat;
                //usuario.Ficha = vista.Ficha;
                usuario.Telefono = vista.Telefono;
                //usuario.Extension = vista.Extension;
                //usuario.Celular = vista.Celular;
                //usuario.DependenciaId = vista.DependenciaId;
                //usuario.Cargo = vista.Cargo;
                //if (!string.IsNullOrEmpty(pic))
                {
                    usuario.Foto = string.Format("~/Content/Fotos/{0}", pic);
                }

                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index","Home");

            }
            return View(vista);
        }



        [Authorize(Roles = "Admin")]
        // GET: Usuarios
        public ActionResult Index()
        {
            var userContext = new ApplicationDbContext();
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(userContext));
            var usuarios = db.Usuarios.ToList();
            var usuariosView = new List<UsuarioIndexView>();

            foreach (var usuario in usuarios)
            {
                var usuarioASP = userManager.FindByEmail(usuario.NombreUsuario);
                usuariosView.Add(new UsuarioIndexView
                {

                Nombre = usuario.Nombre,
                    ApellidoPat = usuario.ApellidoPat,
                    ApellidoMat = usuario.ApellidoMat,
                    NombreUsuario = usuario.NombreUsuario,
                    //Ficha = usuario.Ficha,
                    Telefono = usuario.Telefono,
                    //Extension = usuario.Extension,
                    //Celular = usuario.Celular,
                    ////DependenciaId = usuario.DependenciaId,
                    //Cargo = usuario.Cargo,
                    Foto = usuario.Foto,
                    EsAdmin = usuarioASP != null && userManager.IsInRole(usuarioASP.Id , "Admin"),
                    UsuarioId=usuario.UsuarioId,           
                });
             }

            return View(usuariosView);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult OnOffAdmin(int id)
        {
            var usuario = db.Usuarios.Find(id);
            if (usuario != null)
            {
                var userContext = new ApplicationDbContext();
                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(userContext));
                var usuarioASP = userManager.FindByEmail(usuario.NombreUsuario);

                if (usuarioASP != null)
                {
                    if (userManager.IsInRole(usuarioASP.Id, "Admin"))
                    {
                        userManager.RemoveFromRole(usuarioASP.Id, "Admin");
                    }
                    else
                    {
                        userManager.AddToRole(usuarioASP.Id, "Admin");
                   }
                }
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        // GET: Usuarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }


            return View(usuario);
        }


        [Authorize(Roles = "Admin")]
        // GET: Usuarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UsuarioView UsuarioView)
        {
            if (!ModelState.IsValid)
            {
                return View(UsuarioView);
            }

            //Upload
            string path = string.Empty;
            string pic = string.Empty;

            if (UsuarioView.Foto != null)
            {
                pic = Path.GetFileName(UsuarioView.Foto.FileName);
                path = Path.Combine(Server.MapPath("~/Content/Fotos"), pic);

                UsuarioView.Foto.SaveAs(path); //se guarda la foto local

                using (MemoryStream ms = new MemoryStream()) //se guarda en el servidor la foto
                {
                    UsuarioView.Foto.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                } 
            }

            //Guarda el registro
            var usuario = new Usuario
            {
                Nombre = UsuarioView.Nombre,
                ApellidoPat = UsuarioView.ApellidoPat,
                ApellidoMat = UsuarioView.ApellidoMat,
                NombreUsuario = UsuarioView.NombreUsuario,
                //Ficha = UsuarioView.Ficha,
                Telefono = UsuarioView.Telefono,
                //Extension = UsuarioView.Extension,
                //Celular = UsuarioView.Celular,
                //DependenciaId = UsuarioView.DependenciaId,
                //Cargo = UsuarioView.Cargo,
                //Foto = pic == string.Empty ? string.Empty : string.Format("~/Content/Fotos/{0}", pic)

            };

            db.Usuarios.Add(usuario);

            try
            {
                db.SaveChanges();
                this.CreateASPUser(UsuarioView);

            }
            catch (Exception ex)
            {
                if(ex.InnerException!=null && 
                    ex.InnerException.InnerException!=null && 
                    ex.InnerException.InnerException.Message.Contains("NombreUsuarioIndex"))
                {
                    ViewBag.Error = "El correo ya ha sido utilizado para otro usuario";
                }
                else
                {
                    ViewBag.Error = ex.Message;
                }
                return View(UsuarioView);
            }
       
            return RedirectToAction("Index");

           
        }

        private void CreateASPUser(UsuarioView usuarioView)
        {
            //Administracion de Usuarios
            var userContext = new ApplicationDbContext();
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(userContext));
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(userContext));

            //Crear Role de usuarios
            string roleName = "User";

            //Se verifica que exista el rol, si no existe:
            if (!roleManager.RoleExists(roleName))
            {
               roleManager.Create(new IdentityRole(roleName));
            }

            //Creacion del usuario ASPNet
            var userASP = new ApplicationUser
            {
                UserName = usuarioView.NombreUsuario,
                Email = usuarioView.NombreUsuario,
                PhoneNumber = usuarioView.Telefono,
            };
            userManager.Create(userASP, userASP.UserName);

            //Se agrega usuario al rol
            userASP = userManager.FindByName(usuarioView.NombreUsuario);
            userManager.AddToRole(userASP.Id, "User");

        }

        [Authorize(Roles = "Admin")]
        // GET: Usuarios/Edit/5
        public ActionResult Edit(int? id)
        {

SolVueWeb/Views/Usuarios/Create.cshtml
@model SolVueWeb.Models.UsuarioView

@{
    ViewBag.Title = "Create";
}

<h2>Crear Usuario</h2>
<h3> @ViewBag.Error</h3>


@using (Html.BeginForm("Create", "Usuarios", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoPat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoPat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoPat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoMat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoMat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoMat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Ficha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ficha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ficha, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Extension, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Extension, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Extension, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.DependenciaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DependenciaId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DependenciaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cargo, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                     @Html.TextBoxFor(model => model.Foto, new {Type="file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SolVueWeb/Views/Usuarios/Delete.cshtml
@model SolVueWeb.Models.Usuario

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    @Html.ValidationSummary(true)
   <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApellidoPat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApellidoPat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApellidoMat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApellidoMat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Ficha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ficha)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Extension)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Extension)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DependenciaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DependenciaId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cargo)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Foto))
            {
                <img src="@Url.Content(Model.Foto)" alt="Imagenes de SSG" style="width:100px;height:100px;width:auto;max-height:100px" />
            }
       </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SolVueWeb/Views/Usuarios/Edit.cshtml
@model SolVueWeb.Models.UsuarioView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Usuarios", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Usuario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UsuarioId)
        @Html.HiddenFor(model => model.NombreUsuario)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new  { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoPat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoPat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoPat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoMat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoMat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoMat, "", new { @class = "text-danger" })
            </div>
        </div>


        @*<div class="form-group">
            @Html.LabelFor(model => model.Ficha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ficha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ficha, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Extension, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Extension, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Extension, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DependenciaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DependenciaId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DependenciaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cargo, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(model => model.Foto, new { Type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}