SolVueWeb/Models/Modelo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SolVueWeb.Models
{
    public class Modelo
    {
        [Key]
        public int ModeloId { get; set; }
        [Required(ErrorMessage ="El campo {0} es requerido")]
        [StringLength(50, ErrorMessage ="El campo {0} debe cotener un maximo de {1} y un minnimo de {2} caracteres",MinimumLength =3)]
        public string Nombre { get; set; }
        public virtual ICollection<Matricula> Matriculas { get; set; }
    }
}

SolVueWeb/Controllers/ModelosController.cs
using SolVueWeb.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SolVueWeb.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ModelosController : Controller
    {
        private SolVueContext db = new SolVueContext();
        // GET: Modelos
        [HttpGet]
        public ActionResult Index()
        {
            return View(db.Modelos.ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Modelo modelo)
        {
            if (!ModelState.IsValid)
            {
                return View(modelo);
            }
            db.Modelos.Add(modelo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Se busca rgistro
            var modelo = db.Modelos.Find(id);
            if (modelo == null)
            {
                return HttpNotFound();
            }

            return View(modelo);
        }

        [HttpPost]
        public ActionResult Edit(Modelo modelo)
        {
            if (!ModelState.IsValid)
            {
                return View(modelo);
            }
            db.Entry(modelo).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var modelo = db.Modelos.Find(id);
            if (modelo == null)
            {
                return HttpNotFound();
            }

            var vista = new ModeloDetalleView
            {
                ModeloId = modelo.ModeloId,
                Nombre = modelo.Nombre,
                Matriculas = modelo.Matriculas.ToList(),
            };
            return View(vista);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var modelo = db.Modelos.Find(id);
            if (modelo == null)
            {
                return HttpNotFound();
            }
            return View(modelo);
        }

        [HttpPost]
        public ActionResult Delete(int id, Modelo modelo)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            modelo = db.Modelos.Find(id);
            if (modelo == null)
            {
                return HttpNotFound();
            }
            db.Modelos.Remove(modelo);
           try
            {
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                if(ex.InnerException!=null &&
                    ex.InnerException.InnerException!=null &&
                        ex.InnerException.InnerException.Message.Contains("REFERENCE"))
                        {
                            ViewBag.Error = "No puede borrar el registro ya que tiene registros relacionados";
                         }
                else
                {
                    ViewBag.Error = ex.Message;
                }
                return View(modelo);
            }
            return RedirectToAction("Index");
        }

   
        [HttpGet] 
        public ActionResult ReasignarMatricula(int id)
        {
            var matricula = db.Matriculas.Find(id);
            //var mdloId = matricula.ModeloId;
            //matricula.ModeloId = 7;
            //if (matricula != null)
            //{
            //    db.Entry(matricula).State = EntityState.Modified;
            //    db.SaveChanges();
            //}
            //return RedirectToAction(string.Format("Details/{0}", mdloId));
            //var matriculaView = new MatriculaView
            var matricReasignaView = new MatricReasignaView
            {
                Siglas = matricula.Siglas,
                //Serie = matricula.Serie,
                //AnioFabricacion = matricula.AnioFabricacion,
                //Poseedor = matricula.Poseedor,
                //Capacidad = matricula.Capacidad,
                ModeloId = matricula.ModeloId,
                //Certificado = matricula.Certificado,
                MatriculaId = matricula.MatriculaId,
            };

            ViewBag.MdloId = new SelectList(db.Modelos, "ModeloId", "Nombre", matricula.ModeloId);
            ViewBag.siglas = matricula.Siglas;
            //return View(matriculaView);
            return View(matricReasignaView);


        }

 
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult ReasignarMatricula(MatricReasignaView matricReasignaView)
        {
            if (!ModelState.IsValid)
            {
                return View(matricReasignaView);
            }

        ////Upload Imagen
        //string path = string.Empty;
        //string pic = string.Empty;

        //if (matricReasignaView.Imagen != null)
        //{
        //    pic = Path.GetFileName(matricReasignaView.Imagen.FileName);
        //    path = Path.Combine(Server.MapPath("~/Content/Fotos"), pic);
        //    matriculaView.Imagen.SaveAs(path);
        //    using (MemoryStream ms = new MemoryStream())
        //    {
        //        matriculaView.Imagen.InputStream.CopyTo(ms);
        //        byte[] array = ms.GetBuffer();
        //    }
        //}

        var matricula = db.Matriculas.Find(matricReasignaView.MatriculaId);

            matricula.Siglas = matricReasignaView.Siglas;
            matricula.MatriculaId = matricReasignaView.MatriculaId;
            //matricula.Serie = matriculaView.Serie;
            //matricula.AnioFabricacion = matriculaView.AnioFabricacion;
            //matricula.Poseedor = matriculaView.Poseedor;
            //matricula.Capacidad = matriculaView.Capacidad;
            //matricula.Certificado = matriculaView.Certificado;
            matricula.ModeloId = matricReasignaView.ModeloId;
            //if (!string.IsNullOrEmpty(pic))
            //{
            //    matricula.Imagen = pic == string.Empty ? string.Empty : string.Format("~/Content/Fotos/{0}", pic);
            //}


            db.Entry(matricula).State = EntityState.Modified;
            db.SaveChanges();
            //Message="Se reasigno correctamente el modelo a la matricula";
            ViewBag.MdloId = new SelectList(db.Modelos, "ModeloId", "Nombre", matricula.ModeloId);
            TempData["Correcto"] = "Se asigno correctamente el modelo a la matricula";
            return RedirectToAction(string.Format("Details/{0}",matricula.ModeloId));

        }


        [HttpGet]
        public ActionResult AddMatricula(int modeloId)
        {
            ViewBag.MatriculaId = new SelectList(db.Matriculas.OrderBy(m => m.Siglas), "MatriculaId", "Siglas");
            var vista = new AddMatriculaView
            {
                ModeloId = modeloId,
               
            };
            var nombreModelo = db.Modelos.Find(vista.ModeloId);
            string nombre = nombreModelo.Nombre;
            ViewBag.NombreModelo = nombre;
            return View(vista);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult AddMatricula(AddMatriculaView vista)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.MatriculaId = new SelectList(db.Matriculas.OrderBy(m => m.Siglas), "MatriculaId", "Siglas");
                return View(vista);
            }

            

            var matriculaenmodelo = db.Matriculas.Select(m => m.MatriculaId == vista.MatriculaId && m.ModeloId==vista.ModeloId);
            if (matriculaenmodelo != null)
            {
                ViewBag.MatriculaId = new SelectList(db.Matriculas.OrderBy(m => m.Siglas), "MatriculaId", "Siglas");
                ViewBag.Error = "La matricula ya se encuentra registrada en este modelo";
                return View(vista);
            }

            var matricula = db.Matriculas.Find(vista.MatriculaId ) ;

            if (matricula != null)
            {
                ViewBag.MatriculaId = new SelectList(db.Matriculas.OrderBy(m => m.Siglas), "MatriculaId", "Siglas");
                db.Entry(matricula).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction(string.Format("Details/{0}", vista.ModeloId));
            }

            ViewBag.MatriculaId = new SelectList(db.Matriculas.OrderBy(m => m.Siglas), "MatriculaId", "Siglas");
            return View(vista);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

SolVueWeb/Views/Modelos/Create.cshtml
@model SolVueWeb.Models.Modelo

@{
    ViewBag.Title = "Create";
}

  
<h2>Create</h2>
    

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Modelo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SolVueWeb/Views/Modelos/Delete.cshtml
@model SolVueWeb.Models.Modelo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>@ViewBag.Error</h3>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Modelo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SolVueWeb/Views/Modelos/Details.cshtml
@model SolVueWeb.Models.ModeloDetalleView

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>@string.Format("Modelo:     {0}", Model.Nombre )</h4>
    @*<h5>@Model.Nombre</h5>*@

    @*<dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>*@
</div>

<h5>Matriculas:</h5>

@if(Model.Matriculas.Count==0)
{
   <h4>No hay matriculas registardas para este modelo</h4>
}
else
{
    <table class="table">
        <tr>
             <th>
                @Html.DisplayNameFor(model => Model.Matriculas[0].Siglas )
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.Matriculas[0].Serie )
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.Matriculas[0].AnioFabricacion )
            </th>
              <th>
                @Html.DisplayNameFor(model => Model.Matriculas[0].Capacidad )
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.Matriculas[0].Imagen )
            </th>
            <th></th>
        </tr>

        @if (@TempData["Correcto"] != null)
        {
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h4>¡Ok!</h4>
            @TempData["Correcto"]
        </div>
        }



        @for (int i=0; i<Model.Matriculas.Count;i++ )
        {
            <tr>
               <td>
                    @Html.DisplayFor(modelItem => Model.Matriculas[i].Siglas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Matriculas[i].Serie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Matriculas[i].AnioFabricacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.Matriculas[i].Capacidad)
                </td>
                 <td>
                    @if (!string.IsNullOrEmpty(Model.Matriculas[i].Imagen))
                    {
                        <img src="@Url.Content( Model.Matriculas[i].Imagen)" alt="Image" style="width:100px;height:100px;max-width:100%;height:auto;" />
                    }
                </td>
                <td>
                   @Html.ActionLink("Reasignar", "ReasignarMatricula", new { id = Model.Matriculas[i].MatriculaId }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
 
    </table>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ModeloId }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Agregar Matricula", "AddMatricula", new { modeloId = Model.ModeloId }, new { @class = "btn btn-warning" })
        @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-success" })
    </p>

}

SolVueWeb/Views/Modelos/Edit.cshtml
@model SolVueWeb.Models.Modelo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Modelo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ModeloId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SolVueWeb/Views/Modelos/Index.cshtml
@model IEnumerable<SolVueWeb.Models.Modelo>

@{
    ViewBag.Title = "Index";
}

<h2>Modelos</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create", new { }, new { @class = "btn btn-warning" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ModeloId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ModeloId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ModeloId })
        </td>
    </tr>
}

</table>
<div>
    @Html.ActionLink("Pagina de Inicio","Index", "Home", new { }, new {@class="btn btn-success" })
</div>

SolVueWeb/Views/Modelos/ReasignarMatricula.cshtml
@model SolVueWeb.Models.MatricReasignaView


@{
    ViewBag.Title = "Reasignar Modelo";
}

<h2>Reasignar Modelo</h2>
@using (Html.BeginForm("ReasignarMatricula", "Modelos", FormMethod.Post,  new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
 
    <div class="form-horizontal">
        <h3>@string.Format("Matricula: {0}", ViewBag.siglas) </h3>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MatriculaId)
        @Html.HiddenFor(model => model.Siglas )
        @*@Html.HiddenFor(model => model.ModeloId )*@


        <div class="form-group">
            @Html.LabelFor(model => model.ModeloId, "Modelo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("MdloId", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.DropDownList("ModeloId",ViewBag.MdloId as SelectList )
                @Html.ValidationMessageFor(model => model.ModeloId, "", new { @class = "text-danger" })
            </div>
        </div>

 
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Reasignarar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a Detalles", string.Format("Details/{0}",Model.ModeloId),new { @class = "btn btn-success" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}