SolVueWeb/Models/Matricula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SolVueWeb.Models
{
    public class Matricula
    {
        [Key]
        public int MatriculaId { get; set; }

        [Required(ErrorMessage ="El campo {0} es requerido")]
        [StringLength(30)]
        [Display(Name ="Matrícula")]
        public string Siglas { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(30)]
        public string Serie { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Año de fabricación")]
        public int AnioFabricacion { get; set; }

        [StringLength(50)]
        public string Poseedor { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Capacidad pax")]
        public int Capacidad { get; set; }

         public int ModeloId { get; set; }

        [StringLength(30)]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Cert. de matricula")]
        public string Certificado { get; set; }

        public string Imagen { get; set; }
        public virtual Modelo Modelo { get; set; }

    }
}

SolVueWeb/Models/MatriculaView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SolVueWeb.Models
{
    public class MatriculaView
    {
        public int MatriculaId { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(30)]
        [Display(Name = "Matrícula")]
        public string Siglas { get; set; }
        [StringLength(30)]
        public string Serie { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Año de fabricación")]
        public int AnioFabricacion { get; set; }
        [StringLength(50)]
        public string Poseedor { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name = "Capacidad pax")]
        public int Capacidad { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public int ModeloId { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(30)]
        [Display(Name = "Cert. de matric.")]
        public string Certificado { get; set; }

        public HttpPostedFileBase Imagen{ get; set; }

        public virtual Modelo Modelo { get; set; }

    }
}

SolVueWeb/Controllers/MatriculasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SolVueWeb.Models;
using System.IO;

namespace SolVueWeb.Controllers
{
    [Authorize(Roles ="Admin")]
    public class MatriculasController : Controller
    {
        private SolVueContext db = new SolVueContext();

        // GET: Matriculas
        public ActionResult Index()
        {
            var matriculas = db.Matriculas.Include(m => m.Modelo);
            return View(matriculas.ToList());
        }

        // GET: Matriculas/Details/5   
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matricula matricula = db.Matriculas.Find(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }
            return View(matricula);
        }

        // GET: Matriculas/Create
        public ActionResult Create()
        {
            ViewBag.ModeloId = new SelectList(db.Modelos, "ModeloId", "Nombre");
            return View();
        }

        // POST: Matriculas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MatriculaView matriculaView)
        {
            if (!ModelState.IsValid)
            {
                return View(matriculaView);
            }

            //Upload Imagen
            string path = string.Empty;
            string pic = string.Empty;

            if (matriculaView.Imagen != null)
            {
                pic = Path.GetFileName(matriculaView.Imagen.FileName);
                path = Path.Combine(Server.MapPath("~/Content/Fotos"), pic);
                matriculaView.Imagen.SaveAs(path);
                using(MemoryStream ms=new MemoryStream())
                {
                    matriculaView.Imagen.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                }
            }

           
            //Save Record

            var matricula = new Matricula
            {
                Siglas = matriculaView.Siglas,
                Serie = matriculaView.Serie,
                AnioFabricacion = matriculaView.AnioFabricacion,
                Poseedor = matriculaView.Poseedor,
                Capacidad = matriculaView.Capacidad,
                ModeloId = matriculaView.ModeloId,
                Certificado = matriculaView.Certificado,
                Imagen = pic == string.Empty ? string.Empty : string.Format("~/Content/Fotos/{0}", pic)

            };
            
            db.Matriculas.Add(matricula);

            try
            {
                db.SaveChanges();

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(matriculaView);
            }
            return RedirectToAction("Index");

            //    ViewBag.ModeloId = new SelectList(db.Modelos, "ModeloId", "Nombre", matricula.ModeloId);
            //    return View(matricula);
        }

        // GET: Matriculas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var matricula = db.Matriculas.Find(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }

            var matriculaView = new MatriculaView
            {
                Siglas = matricula.Siglas,
                Serie = matricula.Serie,
                AnioFabricacion = matricula.AnioFabricacion,
                Poseedor = matricula.Poseedor,
                Capacidad = matricula.Capacidad,
                ModeloId = matricula.ModeloId,
                Certificado = matricula.Certificado,
                MatriculaId=matricula.MatriculaId
            };

            ViewBag.ModeloId = new SelectList(db.Modelos, "ModeloId", "Nombre", matricula.ModeloId);
            return View(matriculaView);
        }

        // POST: Matriculas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MatriculaView matriculaView)
        {
            if (!ModelState.IsValid)
            {
               return View(matriculaView);
            }

            //Upload Imagen
            string path = string.Empty;
            string pic = string.Empty;

            if (matriculaView.Imagen != null)
            {
                pic = Path.GetFileName(matriculaView.Imagen.FileName);
                path = Path.Combine(Server.MapPath("~/Content/Fotos"), pic);
                matriculaView.Imagen.SaveAs(path);
                using (MemoryStream ms = new MemoryStream())
                {
                    matriculaView.Imagen.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                }
            }

            var matricula = db.Matriculas.Find(matriculaView.MatriculaId);

            matricula.Siglas = matriculaView.Siglas;
            matricula.Serie = matriculaView.Serie;
            matricula.AnioFabricacion = matriculaView.AnioFabricacion;
            matricula.Poseedor = matriculaView.Poseedor;
            matricula.Capacidad = matriculaView.Capacidad;
            matricula.Certificado = matriculaView.Certificado;
            matricula.ModeloId = matriculaView.ModeloId;
            if (!string.IsNullOrEmpty(pic))
            {
                matricula.Imagen = pic == string.Empty ? string.Empty : string.Format("~/Content/Fotos/{0}", pic);
            }

            ViewBag.ModeloId = new SelectList(db.Modelos, "ModeloId", "Nombre", matricula.ModeloId);
            db.Entry(matricula).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Matriculas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matricula matricula = db.Matriculas.Find(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }
            return View(matricula);
        }

        // POST: Matriculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Matricula matricula = db.Matriculas.Find(id);
            db.Matriculas.Remove(matricula);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SolVueWeb/Views/Matriculas/Create.cshtml
@model SolVueWeb.Models.MatriculaView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<h3>@ViewBag.Error</h3>

@using (Html.BeginForm("Create","Matriculas",FormMethod.Post,new {enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Matricula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Siglas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Siglas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Siglas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Serie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Serie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Serie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnioFabricacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnioFabricacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnioFabricacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poseedor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Poseedor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Poseedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModeloId, "ModeloId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ModeloId","[Seleccione un modelol]")
                @Html.ValidationMessageFor(model => model.ModeloId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Certificado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Certificado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Certificado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file ">
                    @Html.TextBoxFor(modelo => modelo.Imagen, new {type="file"} )
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SolVueWeb/Views/Matriculas/Delete.cshtml
@model SolVueWeb.Models.Matricula

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Esta seguro de borrar esta matricula?</h3>
<div>
    <h4>Matricula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Modelo.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Siglas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Siglas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Serie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnioFabricacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnioFabricacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Poseedor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Poseedor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Certificado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Certificado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Imagen))
            {
                <img src="@Url.Content(Model.Imagen)" alt="Image" style="width:200px;height:200px;max-width:100%;height:auto;" />
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> 
            @Html.ActionLink("Back to List", "Index",new { },new { @class = "btn btn-success" })
        </div>
    }
</div>

SolVueWeb/Views/Matriculas/Details.cshtml
@model SolVueWeb.Models.Matricula

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Matricula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Modelo.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Siglas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Siglas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Serie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnioFabricacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnioFabricacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Poseedor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Poseedor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Certificado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Certificado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Imagen))
            {
                <img src="@Url.Content(Model.Imagen)" alt="Image" style="width:200px;height:200px;max-width:100%;height:auto;" />
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MatriculaId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SolVueWeb/Views/Matriculas/Edit.cshtml
@model SolVueWeb.Models.MatriculaView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Matriculas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Matricula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MatriculaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Siglas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Siglas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Siglas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Serie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Serie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Serie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnioFabricacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnioFabricacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnioFabricacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poseedor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Poseedor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Poseedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capacidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capacidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capacidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModeloId, "ModeloId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ModeloId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModeloId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Certificado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Certificado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Certificado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file ">
                    @Html.TextBoxFor(modelo => modelo.Imagen, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SolVueWeb/Views/Matriculas/Index.cshtml
@model IEnumerable<SolVueWeb.Models.Matricula>

@{
    ViewBag.Title = "Index";
}

<h2>Matrículas</h2>


<p>
    @Html.ActionLink("Crear Nuevo", "Create",new { }, new { @class = "btn btn-warning" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Modelo.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Siglas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Serie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnioFabricacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Poseedor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Capacidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Certificado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imagen)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Siglas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Serie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AnioFabricacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Poseedor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Capacidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Certificado)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.Imagen))
            {
                <img src="@Url.Content(item.Imagen)" alt="Image" style="width:100px;height:100px;max-width:100%;height:auto;" />
            }
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.MatriculaId }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.MatriculaId }) |
            @Html.ActionLink("Borrar", "Delete", new { id=item.MatriculaId })
        </td>
    </tr>
}

</table>
<div>
    @Html.ActionLink("Pagina de Inicio", "Index", "Home", new { }, new { @class = "btn btn-success" })
</div>